[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd backend && npm install --production"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "cd backend && npm start"