[phases.setup]
nixPkgs = ["nodejs-18_x", "python39", "gcc"]

[phases.install]
cmds = [
  "cd backend",
  "npm ci --production --legacy-peer-deps || npm install --production --legacy-peer-deps"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && node server.js"