[phases.setup]
nixPkgs = ["nodejs-18_x", "python39", "gcc"]
nixpkgsArchive = "e05605ec414618eab4a7a6aea8b38f6fbbcc8f08"

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci --production --legacy-peer-deps || npm install --production --legacy-peer-deps"]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'Build complete'"]

[start]
cmd = "node server.js"